package NewLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {

  /*package*/ final ConceptDescriptor myConceptExpression = new ConceptDescriptorBuilder("NewLanguage.structure.Expression", MetaIdFactory.conceptId(0xb99a49e16a384062L, 0x994d7517c056ba6eL, 0x644c8c744a1ee3bdL)).interface_().create();
  /*package*/ final ConceptDescriptor myConceptMethod = new ConceptDescriptorBuilder("NewLanguage.structure.Method", MetaIdFactory.conceptId(0xb99a49e16a384062L, 0x994d7517c056ba6eL, 0x644c8c744a1ee3abL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept", "NewLanguage.structure.Expression").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L), MetaIdFactory.conceptId(0xb99a49e16a384062L, 0x994d7517c056ba6eL, 0x644c8c744a1ee3bdL)).childDescriptors(new ConceptDescriptorBuilder.Link(7227305933110436820L, "expression", MetaIdFactory.conceptId(0xb99a49e16a384062L, 0x994d7517c056ba6eL, 0x644c8c744a1ee3bdL), false, false, false)).children(new String[]{"expression"}, new boolean[]{false}).alias("method", "").create();
  /*package*/ final ConceptDescriptor myConceptMethodCall = new ConceptDescriptorBuilder("NewLanguage.structure.MethodCall", MetaIdFactory.conceptId(0xb99a49e16a384062L, 0x994d7517c056ba6eL, 0x644c8c744a1ee3ecL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept", "NewLanguage.structure.Expression").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L), MetaIdFactory.conceptId(0xb99a49e16a384062L, 0x994d7517c056ba6eL, 0x644c8c744a1ee3bdL)).referenceDescriptors(new ConceptDescriptorBuilder.Ref(7227305933110438979L, "message", MetaIdFactory.conceptId(0xb99a49e16a384062L, 0x994d7517c056ba6eL, 0x644c8c744a1ee3abL), false)).references("message").childDescriptors(new ConceptDescriptorBuilder.Link(7227305933110438977L, "receptor", MetaIdFactory.conceptId(0xb99a49e16a384062L, 0x994d7517c056ba6eL, 0x644c8c744a1ee3bdL), false, false, false)).children(new String[]{"receptor"}, new boolean[]{false}).alias(".", "Llamada de un m\u00e9todo").create();
  /*package*/ final ConceptDescriptor myConceptObjectDeclaration = new ConceptDescriptorBuilder("NewLanguage.structure.ObjectDeclaration", MetaIdFactory.conceptId(0xb99a49e16a384062L, 0x994d7517c056ba6eL, 0x644c8c744a181f90L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).childDescriptors(new ConceptDescriptorBuilder.Link(7227305933110436882L, "methods", MetaIdFactory.conceptId(0xb99a49e16a384062L, 0x994d7517c056ba6eL, 0x644c8c744a1ee3abL), true, true, false)).children(new String[]{"methods"}, new boolean[]{true}).alias("object", "Una declaraci\u00f3n de un objeto").create();
  /*package*/ final ConceptDescriptor myConceptObjectReference = new ConceptDescriptorBuilder("NewLanguage.structure.ObjectReference", MetaIdFactory.conceptId(0xb99a49e16a384062L, 0x994d7517c056ba6eL, 0x644c8c744a1ee401L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "NewLanguage.structure.Expression").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xb99a49e16a384062L, 0x994d7517c056ba6eL, 0x644c8c744a1ee3bdL)).referenceDescriptors(new ConceptDescriptorBuilder.Ref(7227305933110436866L, "declaration", MetaIdFactory.conceptId(0xb99a49e16a384062L, 0x994d7517c056ba6eL, 0x644c8c744a181f90L), false)).references("declaration").create();
  /*package*/ final ConceptDescriptor myConceptProgram = new ConceptDescriptorBuilder("NewLanguage.structure.Program", MetaIdFactory.conceptId(0xb99a49e16a384062L, 0x994d7517c056ba6eL, 0x644c8c744a130cbeL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).childDescriptors(new ConceptDescriptorBuilder.Link(7227305933109993367L, "objectDefinitions", MetaIdFactory.conceptId(0xb99a49e16a384062L, 0x994d7517c056ba6eL, 0x644c8c744a181f90L), true, true, false)).children(new String[]{"objectDefinitions"}, new boolean[]{true}).alias("program", "").create();

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptExpression, myConceptMethod, myConceptMethodCall, myConceptObjectDeclaration, myConceptObjectReference, myConceptProgram);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0k, conceptFqName)) {
      case 0:
        return myConceptExpression;
      case 1:
        return myConceptMethod;
      case 2:
        return myConceptMethodCall;
      case 3:
        return myConceptObjectDeclaration;
      case 4:
        return myConceptObjectReference;
      case 5:
        return myConceptProgram;
      default:
        return null;
    }
  }
  private static String[] stringSwitchCases_1htk8d_a0a0k = new String[]{"NewLanguage.structure.Expression", "NewLanguage.structure.Method", "NewLanguage.structure.MethodCall", "NewLanguage.structure.ObjectDeclaration", "NewLanguage.structure.ObjectReference", "NewLanguage.structure.Program"};
}
