package NewLanguage.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.interpreted.BehaviorAspectInterpreted;

public class BehaviorAspectDescriptor implements jetbrains.mps.smodel.runtime.BehaviorAspectDescriptor {
  public BehaviorAspectDescriptor() {
  }
  public BehaviorDescriptor getDescriptor(String fqName) {
    switch (Arrays.binarySearch(stringSwitchCases_846f5o_a0a0b, fqName)) {
      case 4:
        return new Program_BehaviorDescriptor();
      case 2:
        return new ObjectDeclaration_BehaviorDescriptor();
      case 0:
        return new Method_BehaviorDescriptor();
      case 1:
        return new MethodCall_BehaviorDescriptor();
      case 3:
        return new ObjectReference_BehaviorDescriptor();
      default:
        return BehaviorAspectInterpreted.getInstance().getDescriptor(fqName);
    }
  }
  private static String[] stringSwitchCases_846f5o_a0a0b = new String[]{"NewLanguage.structure.Method", "NewLanguage.structure.MethodCall", "NewLanguage.structure.ObjectDeclaration", "NewLanguage.structure.ObjectReference", "NewLanguage.structure.Program"};
}
