package NewLanguage.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class ObjectReference_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements Expression_BehaviorDescriptor {
  public ObjectReference_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "NewLanguage.structure.ObjectReference";
  }
}
